name: deploy-github-action
on: [workflow_dispatch]
jobs:
  install-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}
  build:
    runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '18'
        - name: npm build
          run: npm ci
          run: npm run build
          run: npm test

  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: Enviroment for PHP
        uses: shivammathur/setup-php@v2
        with: 
            php-version: '7.4'
            #extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
            tools: composer:v2
            coverage: none
        env: 
          update: true
      - name: validate composer.json and composer.lock
        run: composer validate

      - name: composer install
        run: composer install --no-dev --no-progress --no-scripts --prefer-dist -a
      - name: deploy 
        run: rsync -azP --exclude '.env' --exclude '.env.local' --exclude '.env.test' ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/web